### ISSUE TITLE
Moving to WebTransport

### ISSUE THREAD

**Issue by jianjunz** [open-webrtc-toolkit/owt-sdk-quic#26]
quic-transport will no longer be supported by browser. Moving to HTTP/3 based WebTransport to align with spec.

**Comment by guest271314** [comment]
Can we use this as server code for HTTP/3 over `WebTransport`? Are there any examples? See https://github.com/GoogleChrome/samples/issues/718.

**Comment by jianjunz** [comment]
Implementation of HTTP/3 over WebTransport is still working in progress. Please see #29 for its latest status. Thanks.

**Comment by guest271314** [comment]
What are you using now? 

Does this repository currently use the deprecated/removed `quic-transport` isolated from Chromium source code?

I was using `QuicTransport`/`quic-transport` https://github.com/guest271314/quictransport prior to deprecation and am curious if the Chromium source code can be farmed out to its own module so that the code can still be used?

**Comment by jianjunz** [comment]
This repository currently uses quic-transport.

Public APIs provided by this SDK doesn't involve Chromium's header files, but the implementation is based on Chromium source code. So developers of this repository need to pull Chromium source code for compiling, while users don't.

**Comment by jianjunz** [comment]
Main branch is moved to WebTransport over HTTP/3.
